global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email'
receivers:
  - name: 'email'
    email_configs:
      - to: example@example.com
        from: 'Alert Manager <no-reply@example.com>'
        smarthost: smtp.example.com:587
        #require_tls: true
        auth_username: example@example.com
        auth_identity: example@example.com
        auth_password: MyPassword
        send_resolved: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
