version: '3.8'
services:
  # InfluxDB
  influxdb:
    container_name: 'influxdb'
    image: influxdb:2.0-alpine
    security_opt:
      - no-new-privileges:true
    networks:
      ingest:
        ipv4_address: 172.16.1.202
    ports:
      - 8086:8086
    environment:
      INFLUXD_REPORTING_DISABLED: 'true'
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: '{{ influx_username }}'
      DOCKER_INFLUXDB_INIT_PASSWORD: '{{ influx_password }}'
      DOCKER_INFLUXDB_INIT_ORG: '{{ influx_org }}'
      DOCKER_INFLUXDB_INIT_BUCKET: '{{ influx_bucket }}'
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: '{{ influx_admin_token }}'
      V1_DB_NAME: '{{ influx_bucket }}'
      V1_RP_NAME: '{{ influx_username }}'
      V1_AUTH_USERNAME: '{{ influx_username }}'
      V1_AUTH_PASSWORD: '{{ influx_password }}'
    volumes:
      - /opt/influxdb/scripts:/docker-entrypoint-initdb.d
      - /opt/influxdb/data:/var/lib/influxdb2
      - /opt/influxdb/backups:/backups
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  # Mosquitto
  mosquitto:
    container_name: 'mosquitto'
    image: eclipse-mosquitto:openssl
    security_opt:
      - no-new-privileges:true
    networks:
      ingest:
        ipv4_address: 172.16.1.201
    ports:
      - 1883:1883
    volumes:
      - /opt/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /opt/mosquitto/data:/mosquitto/data
      - /opt/mosquitto/passwd:/mosquitto/passwd
      - /opt/shared:/shared

  #  telegraf - InfluxDB Importer
  telegraf:
    container_name: 'telegraf'
    image: telegraf:1.17-alpine
    restart: unless-stopped
    networks:
      ingest:
        ipv4_address: 172.16.1.203
    security_opt:
      - no-new-privileges:true
    volumes:
      - /opt/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - 'traefik.enable=false'

  api:
    image: ghcr.io/dylangore-fyp/api:latest
    container_name: api
    restart: unless-stopped
    networks:
      - ingest
    ports:
      - 5000:5000
    security_opt:
      - no-new-privileges:true
    environment:
      INFLUX_HOST: '{{ api_influx_host }}'
      INFLUX_PORT: '{{ api_influx_port }}'
      INFLUX_DATABASE: '{{ api_influx_database }}'
      INFLUX_USER: '{{ api_influx_username }}'
      INFLUX_PASSWORD: '{{ api_influx_password }}'
      INFLUX_ADMIN_UID: '{{ api_admin_uid }}'
      ENABLE_METRICS: '{{ api_enable_metrics }}'

    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /opt/vehicles/api/serviceAccountKey.json:/fyp-api/serviceAccountKey.json:ro

  dashboard:
    image: ghcr.io/dylangore-fyp/dashboard:latest
    container_name: dashboard
    restart: unless-stopped
    networks:
      - ingest
    ports:
      - 80:80
    security_opt:
      - no-new-privileges:true
    environment:
      VITE_FIREBASE_API_KEY: '{{ dashboard_firebase_api_key }}'
      VITE_AUTH_DOMAIN: '{{ dashboard_auth_domain }}'
      VITE_PROJECT_ID: '{{ dashboard_project_id }}'
      VITE_STORAGE_BUCKET: '{{ dashboard_storage_bucket }}'
      VITE_MESSAGING_SENDER_ID: '{{ dashboard_message_sender_id }}'
      VITE_APP_ID: '{{ dashboard_app_id }}'
      VITE_ENABLE_USER_REGISTRATION: '{{ dashboard_enable_user_registration }}'
      VITE_API_LOCATION: '{{ dashboard_api_location }}'
      VITE_LOGIN_PROVIDERS: '{{ dashboard_login_providers }}'
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    networks:
      - ingest
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    security_opt:
      - no-new-privileges:true
    environment:
      PUID: 1001
      PGID: 1001
    volumes:
      - /opt/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /opt/prometheus/rules.yml:/etc/prometheus/rules.yml:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-admin-api'

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: unless-stopped
    networks:
      - ingest
    security_opt:
      - no-new-privileges:true
    environment:
      PUID: 1001
      PGID: 1001
    volumes:
      - /opt/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - /opt/alertmanager:/etc/alertmanager
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9093:9093
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      # - '--web.external-url=https://alerts.example.com'

networks:
  ingest:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/24
