global:
  scrape_interval: 60s
  evaluation_interval: 60s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - 'rules.yml'

scrape_configs:
  - job_name: 'host'
    static_configs:
      - targets: ['host.docker.internal:9100']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'api'
    static_configs:
      - targets: ['api:5000']
  # - job_name: 'traefik'
  #   static_configs:
  #     - targets: ['traefik:8080']
